spring:
  application:
    name: sentinel-api
  
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/sentinel_db
    username: sentinel
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
      embedding:
        options:
          model: nomic-embed-text 
    
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true

sentinel:
  ratelimit:
    strategy: bucket  # Change to 'rigid' to use the old implementation
    #strategy: rigid  # Change to 'bucket' to use the new implementation