/**
 * 
 */
package com.sentinel.api.model;

/**
 * A Data Transfer Object (DTO) representing a discrete, metadata-enriched fragment 
 * of a reactive Large Language Model (LLM) stream.
 * * <p><b>Main Purpose:</b></p>
 * In standard LLM streaming, tokens are emitted as raw, unstructured text strings 
 * (often heavily fragmented). This record acts as the "Architectural Supremacy Layer," 
 * intercepting raw tokens and wrapping them into a structured JSON-serializable payload 
 * before they reach the WebSocket boundary.
 * * <p><b>Encapsulated Details:</b></p>
 * <ul>
 * <li><b>content:</b> The actual string fragment generated by the LLM (e.g., " archi", "tecture").</li>
 * <li><b>type:</b> The routing metadata ({@link ChunkType}). This allows the frontend client to 
 * perform state transitions (e.g., rendering a loading spinner, initializing a Mermaid.js canvas, 
 * or closing the connection) without needing to parse or regex the raw text stream itself.</li>
 * <li><b>timestamp:</b> The epoch time of emission, enabling client-side latency tracking and 
 * re-sequencing if necessary.</li>
 * </ul>
 * * @see ChunkType
 */
public record SentinelChunk(
	    String content,
	    ChunkType type,
	    long timestamp
	) {
	    public enum ChunkType {
	        TEXT,
	        /**
	         * SENTINEL ANALYSIS STARTING
	         */
	        DIAGRAM_START, 
	        /**
	         * ANALYSIS COMPLETE
	         */
	        ANALYSIS_COMPLETE,
	        
	        /**
	         * @since Day7
	         */
	        RATE_LIMIT_EXCEEDED,
	    }
}
