name: Bake AI Image

on:
  workflow_dispatch: # Manual trigger
  push:
    paths:
      - 'Ollama.Dockerfile' # Only rebuild if the recipe changes

jobs:
  bake:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          #file: ./Ollama.Dockerfile
          file: sentinel/sentinel-api/src/test/resources/Ollama.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sentinel/sentinel-ollama-llama3:latest
          # This magic line uses GitHub's native cache for Docker layers
          cache-from: type=gha
          cache-to: type=gha,mode=max