name: Sentinel API CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sentinel-api/**' # Only run if changes are made to the API folder
      - '.github/workflows/**' # Verify we did'nt break anything modifying workflows themselves.
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      # We move into the sub-folder before running the build
      run: mvn -B clean test
      working-directory: ./sentinel-api

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always() # Run even if tests fail to show what went wrong
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'